# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

branches:
    only:
        - main
        - master
        - dev

language: R
cache: packages

r_packages:
    - covr

warnings_are_errors: false

after_success:
    - Rscript -e 'covr::codecov()'
