#' Strip business legal entity type from name
#'
#' @param string A character vector.
#' @param trim_ws A boolean; determines if trailing white spaces (potentially
#'   generated by the replacement), are trimmed or not.
#'
#' @return A character vector.
#' @export
#'
#' @examples
#' strip_business_legal_entity_type("Farmer Box Plc.")
#'
#' @importFrom stringr str_replace str_trim
#' @importFrom purrr when
strip_business_legal_entity_type <- function(string, trim_ws = TRUE) {
  pattern <- "(?:^|\\b)(?:Incorporated|[Ll]imited|P\\.C|[Ll][Tt][Dd]|[Pp][Ll]{1,2}[Cc])\\.?"
  string %>%
    str_replace(., pattern, "") %>%
    when(trim_ws ~ str_trim(.),
         ~.
    )
}

strip_business_legal_entity_type("The limited Arms")
