# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title parse_nested_records
#' @description 
#' Deduplicate and optionally change separators in nested records.
#' @name parse_nested_records
#' @param s a vector of strings
#' @param sep_from string separator in input strings
#' @param sep_to string separator in output strings
#'
#' @export
parse_nested_records <- function(s, sep_from, sep_to) {
    .Call(`_sabre_parse_nested_records`, s, sep_from, sep_to)
}

